### PR TITLE
Use `value` instead `default` keyword in with-shim build option

### LINKED ISSUE #11: meson fails
```
+ exec meson setup --prefix /usr --libdir /usr/lib --libexecdir /usr/lib --bindir /usr/bin --sbindir /usr/bin --includedir /usr/include --datadir /usr/share --mandir /usr/share/man --infodir /usr/share/info --localedir /usr/share/locale --sysconfdir /etc --localstatedir /var --sharedstatedir /var/lib --buildtype release --warnlevel 2 --wrap-mode nofallback linux-steam-integration-0.4 build -Dwith-shim=replacement -Dwith-frontend=true -Dwith-steam-binary=/usr/lib/steam/steam -D b_lto=true
The Meson build system
Version: 0.43.0
Source dir: /mnt/hdd/aur/maintained-packages/linux-steam-integration/src/linux-steam-integration-0.4
Build dir: /mnt/hdd/aur/maintained-packages/linux-steam-integration/src/build
Build type: native build

Meson encountered an error in file meson_options.txt, line 1, column 0:
Invalid kwargs for option "with-shim": "default"

A full log can be found at /mnt/hdd/aur/maintained-packages/linux-steam-integration/src/build/meson-logs/meson-log.txt
```
meson version is 0.43.0

Removing the `default` keyword plus value works
```
--- src/linux-steam-integration-0.4/meson_options.txt   2017-10-11 01:32:29.000000000 +0200
+++ meson_options.txt   2017-10-11 10:33:18.994398657 +0200
@@ -1,4 +1,4 @@
-option('with-shim', type : 'combo', choices : ['replacement', 'co-exist', 'none'], default: 'replacement',
+option('with-shim', type : 'combo', choices : ['replacement', 'co-exist', 'none'],
        description : 'control how the shim is deployed')
 option('with-steam-binary', type: 'string', description: 'Set the path to the Steam binary', value: '/usr/lib/steam/steam')
 option('with-frontend', type: 'boolean', description: 'Build the LSI Settings UI', value: false)
```

### PR DESCRIPTION
**Pull request by alunux**
Fix #11

### CODE REVIEW

**Comment by ikeydoherty** [comment]
Oops - thanks bud!

**Comment by ikeydoherty** [comment]
I assume the Arch package is yours? If so you'll want to take the CXX ABI patch and set `-Dwith-new-libcxx-abi=true` to ensure `LD_PRELOAD` is set when native runtime is disabled (running old crappy games basically). If not it'll be in a new point release which tbh I'm likely to end up doing today

**Comment by alunux** [comment]
@ikeydoherty I'm at Fedora 26. What happened to Arch package?

**Comment by ikeydoherty** [comment]
Oh right. Well - looks like your patch was used in the Arch package update - sorta assumed it was you lol. Do you have an active COPR? I'd like to list the various LSI repos on the main README :)

**Comment by alunux** [comment]
@ikeydoherty Are you an Archer now? xD Yes, I do, but I have not upgraded to v0.4.

**Comment by ikeydoherty** [comment]
Oh I'm no Archer :P The package isn't mine lol. I try to track where my software is in the wider ecosystem :)

**Comment by alunux** [comment]
@ikeydoherty lol, i see lot of Archer out there, e.g. at budgie-desktop issues.

**Comment by ikeydoherty** [comment]
Tada https://github.com/solus-project/linux-steam-integration#getting-lsi

**Comment by alunux** [comment]
@ikeydoherty OMG! Thank you, man. Your softwares are too awesome. I use LSI and Budgie every day, but I don't know why I'm still using Fedora :|

**Comment by ikeydoherty** [comment]
We'll steal you soon enough @alunux :D

**Comment by z3ntu** [comment]
I'm maintaining the Arch package ^^ will make the changes you proposed

**Comment by ikeydoherty** [comment]
merci :)

**Pull request merged**
